### PR TITLE
IMPR: added markdown support for product description

### PR DESCRIPTION
**Pull request by fzngagan**

### CODE REVIEW

**Comment by fzngagan** [comment]
I'm aware of the test fails. There's some issue with my test environment. I'll fix these once my env is fixed.

**Comment by fzngagan** [comment]
@justindirose 
The rubocop error isn't related to my code.

**Comment by justindirose** [comment]
Looks like a relatively safe change. I'm aware of the rubocop error - it's on my list to fix.

Bugs:

1. On `/s/prod_<id>`, the text does not render properly. It shows up as `<strong>Text</strong>` instead of **Text**. 

image

Other than that it looks okay to me!

**Comment by fzngagan** [comment]
@justindirose 
I realized that discourse cooks the markdown before persisting it, which prevents cooking on every client request. Would it be better to do so here too?
That would cause the html to be saved in the stripe.com product description instead of markdown though. Would that be ok?

**Comment by justindirose** [comment]
Ideally that would be nice, but I believe Stripe has character limits on the fields, so we'd easily blow that on a longer description. If we went that route, we'd probably want to store the cooked/raw text locally in the database and send Stripe the Markdown version.

However, since this route isn't as high traffic as topics are, I think this is safe to proceed on as is.

**Review by justindirose — APPROVED** [review]

**Pull request merged**
