### PR TITLE
Import Utility for Procourse-Created Stripe Transactions

### PR DESCRIPTION
**Pull request by kimardenmiller**
- Rake file imports Stripe transactions created by Procourse Memberships plugin.
- Note: Rake file executed thru twice in our usage, but we don't see anything we're doing differently from `subscriptions.rake`. Double execution did not do anything harmful, but was simply an inconvenience.

### CODE REVIEW

**Comment by kimardenmiller** [comment]
Thoughts on approving this PR?

**Review by justindirose — COMMENTED** [review]
Overall, it looks good to me. One bigger picture question: I do see this duplicates a lot of code from https://github.com/discourse/discourse-subscriptions/blob/main/lib/tasks/subscriptions.rake

Is there a reason this couldn't be merged with the existing rake task file, adding some different checks for ProCourse Memberships entries in Stripe?

Ideally, it would be great to keep the tasks DRY and make improvements to the existing rake task at the same time.

**Comment by kimardenmiller** [comment]
I guess I'm not completely clear on the purpose of the other rake task. It was created to migrate from an earlier plugin version?

We've extensively tested our rake utility and know it's solid. While I'm willing to hear how we might merge these two, I'm a little anxious about introducing bugs since we don't have any data against which to test it.

**Comment by justindirose** [comment]
>I guess I'm not completely clear on the purpose of the other rake task. It was created to migrate from an earlier plugin version?

It was but it does essentially the same thing with a few minor logic tweaks. This could also be used to import Stripe products used elsewhere that you want to allow users to purchase through this plugin.

> We've extensively tested our rake utility and know it's solid. While I'm willing to hear how we might merge these two, I'm a little anxious about introducing bugs since we don't have any data against which to test it.

I hear that - but in looking at the original rake task I linked, the only logical function that's different is L127-137 in the PCM import task, which is to make the Stripe objects compatible with Subscriptions. I don't see you pulling from the PluginStore which is where PCM stored a lot of its local data. So in my mind it should be relatively straightforward to merge the two scripts (pull the appropriate info from Stripe, add a check to see if there's missing metadata, then add the missing metadata). 

I understand you have this working, but it makes sense from a maintenance standpoint to extend or maintain one set of code, versus keeping two scripts that do basically the same thing with minor differences.

**Comment by kimardenmiller** [comment]
See your point; this code is not dependent on anything other then the Stripe data itself.

I’m willing to do the merge if you are willing to do the code review to check for any potential bugs I may end up creating. I’m more confident in my ability to carefully test than I am on publishing uncompiled code, but then again I don’t write code for a living ;-)

**Comment by justindirose** [comment]
Would it be difficult to create Subscriptions/PCM subscriptions on a test Stripe instance? That's all you'd likely need for testing out the merge. I unfortunately can't commit to doing that myself at this point.

**Pull request closed without merging**
